- name: Download CRI-O repository 1
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/devel:kubic:libcontainers:stable.repo
    dest: /etc/yum.repos.d
    force: true
    mode: '0644'

- name: Download CRI-O repository 2
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ version }}/{{ os }}/devel:kubic:libcontainers:stable:cri-o:{{ version }}.repo
    dest: /etc/yum.repos.d
    force: true
    mode: '0644'

- name: Installing CRI-O
  ansible.builtin.yum:
    name: cri-o
    state: installed

- name: Start and enable CRI-O
  ansible.builtin.service:
    name: crio
    state: started
    enabled: true
