#--------------------------------------------------------------------------------------#
# This file tracks currently logged user and various Passwords used in this repository #
#--------------------------------------------------------------------------------------#

# NOTE: Since this repository is for demonstration and learning needs passwords have been set in clear text
# NOTE: For greater security please use Vault encrypted password values

# Users sudo password of the user running Ansible on the host machine. (May Require sudoers configuration)
sudo_password: GobbleDeGook              # PLEASE CHANGE THIS


# Username used for Ansible provisioning. This user will be created on all VMs
ssh_user_name: 'ansible'                 # PLEASE CHANGE THIS to suit your requirements

# Gets the name of the current user logged on to the Host
loggedin_user: "{{lookup('env', 'USER')}}"
